### PR TITLE
Handle serviceDown events.

### LINKED ISSUE #54: Web Thing going away can result in a flooded network even if never paired
to reproduce:

1. start a gateway
2. start a wireshark capture
3. start a web thing
4. stop the web thing
5. note in wireshark a flood of thousands of requests from the gateway to the thing that no longer exists

this continues until the web thing comes back or the gateway is rebooted.

if a different web thing is started on the same machine, the flood will not abate if the GET requests are not precisely compatible with the previous web thing.

### PR DESCRIPTION
**Pull request by mrstegeman**
When an mDNS service goes down, remove the linked device. If a
service does not send out a notification that it's going down, it
will automatically expire at the TTL in the service record, which
tends to be quite short.

Fixes #54

### CODE REVIEW

File: thing-url-adapter.js [hunk 1]
```diff
@@ -145,21 +150,24 @@ class ThingURLDevice extends Device {
...
-      this.ws.removeAllListeners('error');
+    if (this.ws !== null) {
+      this.closingWs = true;
 
       if (this.ws.readyState === WebSocket.OPEN) {
         this.ws.close();
       }
 
-      this.ws = null;
+      // Allow the cleanup code in createWebsocket to handle shutdown
```
Comment (hobinjk) [inline thing-url-adapter.js]: The cleanupAndReopen code should be updated to null `this.ws` then for paranoia's sake.

Comment (mrstegeman) [reply thing-url-adapter.js]: Fair point. Done.

Comment (hobinjk) [reply thing-url-adapter.js]: :+1:
